### PR TITLE
feat(rpc): Add RPC endpoint for Fungible Tokens

### PR DESCRIPTION
**Pull request by obycode**
Opening this new PR to wrap up #209 (since I was unable to push to Scott's branch). My commits should resolve the remaining issues.

### CODE REVIEW

**Comment by obycode** [comment]
Looks like I broke some other tests when fixing the others. These should all be easy, I'll fix them.

**Review by fpbgg — APPROVED** [review]

**Comment by obycode** [comment]
Ok, those tests should be fixed now. Sorry about that.

**Review by kantai — APPROVED** [review]
LGTM!

**Review by fpbgg — APPROVED** [review]

**Comment by kantai** [comment]
🚀

**Pull request merged**
